"""add unique constraints on grades bonus_task_id and homework_id

Revision ID: f3db6d5e71bd
Revises: 0002
Create Date: 2026-03-02 18:57:14.819728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_grades_bonus_task_id', ['bonus_task_id'])
        batch_op.create_unique_constraint('uq_grades_homework_id', ['homework_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_grades_homework_id', type_='unique')
        batch_op.drop_constraint('uq_grades_bonus_task_id', type_='unique')

    # ### end Alembic commands ###
