"""add family_members and gateways tables, add tutor_id to subjects

Revision ID: 03989f318419
Revises: 77e62b90ce6e
Create Date: 2026-02-16 20:28:47.283300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03989f318419'
down_revision: Union[str, Sequence[str], None] = '77e62b90ce6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PARENT', 'STUDENT', 'TUTOR', 'RELATIVE', name='familyrole'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('NOT (is_student = 1 AND is_admin = 1)', name='check_student_not_admin'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_single_student', 'family_members', ['is_student'], unique=True, sqlite_where=sa.text('is_student = 1'))
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'WHATSAPP', 'DISCORD', 'SLACK', 'SIGNAL', 'IMESSAGE', 'MSTEAMS', 'MATRIX', name='channeltype'), nullable=False),
    sa.Column('channel_uid', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'channel_uid', name='uq_channel_uid')
    )
    op.create_index('uq_default_per_member', 'gateways', ['family_member_id'], unique=True, sqlite_where=sa.text('is_default = 1'))
    with op.batch_alter_table('subjects') as batch_op:
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subjects_tutor_id', 'family_members', ['tutor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects') as batch_op:
        batch_op.drop_constraint('fk_subjects_tutor_id', type_='foreignkey')
        batch_op.drop_column('tutor_id')
    op.drop_index('uq_default_per_member', table_name='gateways', sqlite_where=sa.text('is_default = 1'))
    op.drop_table('gateways')
    op.drop_index('uq_single_student', table_name='family_members', sqlite_where=sa.text('is_student = 1'))
    op.drop_table('family_members')
    # ### end Alembic commands ###
