"""add_secrets_table

Revision ID: 55c47cfedecb
Revises: ee793270e1d2
Create Date: 2026-02-21 23:06:55.391437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c47cfedecb'
down_revision: Union[str, Sequence[str], None] = 'ee793270e1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###

    # Seed initial secret entries (all with NULL values)
    conn = op.get_bind()
    seeds = [
        ("EDUPAGE_USERNAME", "EduPage account email/username"),
        ("EDUPAGE_PASSWORD", "EduPage account password"),
        ("EDUPAGE_SUBDOMAIN", "EduPage school subdomain (e.g. zsluhacovice)"),
    ]
    for key, description in seeds:
        conn.execute(sa.text(
            "INSERT INTO secrets (key, value, description, "
            "created_at, updated_at) "
            "VALUES (:key, NULL, :desc, datetime('now'), datetime('now'))"
        ), {"key": key, "desc": description})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    # ### end Alembic commands ###
