"""initial

Revision ID: 8a42871ab398
Revises: 
Create Date: 2026-02-16 19:30:56.799637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a42871ab398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_funds',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('available_tasks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_bonus_funds_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('summary_path', sa.String(length=500), nullable=True),
    sa.Column('contents_path', sa.String(length=500), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school', sa.Enum('UA', 'CZ', 'DE', 'FR', 'GB', 'ES', 'IT', 'PL', 'NL', 'US', 'CA', 'AR', 'BR', 'AU', 'CN', 'IN', name='schooltype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_book_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('grade_level IS NULL OR (grade_level >= 1 AND grade_level <= 20)', name='check_grade_level_range'),
    sa.ForeignKeyConstraint(['current_book_id'], ['books.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school', 'name', 'grade_level', name='uq_subject_school_name_grade')
    )
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_key', sa.String(length=10), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grade_minutes', sa.Integer(), nullable=False),
    sa.Column('homework_bonus_minutes', sa.Integer(), nullable=False),
    sa.Column('penalty_minutes', sa.Integer(), nullable=False),
    sa.Column('carryover_out_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_played_minutes', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_key')
    )
    op.create_table('subject_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.Enum('RESOLVED', 'SKIPPED', 'NO_LONGER_RELEVANT', name='closereason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'description', name='uq_subject_topic_subject_description')
    )
    op.create_table('bonus_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_topic_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='bonustaskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['bonus_funds.id'], ),
    sa.ForeignKeyConstraint(['subject_topic_id'], ['subject_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_topic_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'OVERDUE', name='homeworkstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommended_grade', sa.Enum('EXCELLENT', 'GOOD', 'SATISFACTORY', 'POOR', 'FAIL', name='gradevalue'), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('edupage_id', sa.String(length=50), nullable=True),
    sa.Column('reminded_d2_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_d1_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_topic_id'], ['subject_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edupage_id')
    )
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_topic_id', sa.Integer(), nullable=True),
    sa.Column('bonus_task_id', sa.Integer(), nullable=True),
    sa.Column('homework_id', sa.Integer(), nullable=True),
    sa.Column('grade_value', sa.Enum('EXCELLENT', 'GOOD', 'SATISFACTORY', 'POOR', 'FAIL', name='gradevalue'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edupage_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bonus_task_id'], ['bonus_tasks.id'], ),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_topic_id'], ['subject_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edupage_id')
    )
    op.create_table('topic_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_topic_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REINFORCED', name='topicreviewstatus'), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_topic_id'], ['subject_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_reviews')
    op.drop_table('grades')
    op.drop_table('bonuses')
    op.drop_table('homeworks')
    op.drop_table('bonus_tasks')
    op.drop_table('subject_topics')
    op.drop_table('weeks')
    op.drop_table('subjects')
    op.drop_table('books')
    op.drop_table('bonus_funds')
    # ### end Alembic commands ###
