"""Remove penalty_applied from grades

Revision ID: 8c14fc7de7b9
Revises: a0868a9c8f93
Create Date: 2026-02-06 19:36:25.632506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c14fc7de7b9'
down_revision: Union[str, Sequence[str], None] = 'a0868a9c8f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'penalty_applied')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('penalty_applied', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
