"""add birth_date to family_members

Revision ID: a5ceb6f55dea
Revises: bc97c235ffa3
Create Date: 2026-02-21 15:32:27.544943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ceb6f55dea'
down_revision: Union[str, Sequence[str], None] = 'bc97c235ffa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
