"""bonus nullable homework add reason

Revision ID: bc97c235ffa3
Revises: d19fd2fa81b3
Create Date: 2026-02-21 12:42:58.421813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc97c235ffa3'
down_revision: Union[str, Sequence[str], None] = 'd19fd2fa81b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.alter_column('homework_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Delete ad-hoc bonuses that have no homework_id (cannot survive NOT NULL)
    op.execute("DELETE FROM bonuses WHERE homework_id IS NULL")
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.alter_column('homework_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('reason')
