"""add_contents_path_to_books

Revision ID: cd1012057b20
Revises: b491c39a36b3
Create Date: 2026-02-13 19:24:40.290680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1012057b20'
down_revision: Union[str, Sequence[str], None] = 'b491c39a36b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('contents_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'contents_path')
    # ### end Alembic commands ###
