"""add original_value to grades

Revision ID: d19fd2fa81b3
Revises: b92c3c323049
Create Date: 2026-02-20 22:40:57.095117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19fd2fa81b3'
down_revision: Union[str, Sequence[str], None] = 'b92c3c323049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('original_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'original_value')
    # ### end Alembic commands ###
