"""add_sync_providers_table

Revision ID: d65309f12f28
Revises: 55c47cfedecb
Create Date: 2026-02-22 07:54:43.216316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65309f12f28'
down_revision: Union[str, Sequence[str], None] = '55c47cfedecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('is_active = 0 OR school_id IS NOT NULL', name='ck_active_requires_school'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###

    # Seed EduPage provider (inactive, no school linked)
    conn = op.get_bind()
    conn.execute(sa.text(
        "INSERT INTO sync_providers (code, name, is_active, school_id, "
        "created_at, updated_at) "
        "VALUES (:code, :name, 0, NULL, datetime('now'), datetime('now'))"
    ), {"code": "edupage", "name": "EduPage"})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_providers')
    # ### end Alembic commands ###
