"""add_original_filename_to_books

Revision ID: e626294affbc
Revises: b7c27289edc4
Create Date: 2026-02-12 20:02:39.800468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e626294affbc'
down_revision: Union[str, Sequence[str], None] = 'b7c27289edc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default for existing rows, then remove it
    op.add_column(
        'books',
        sa.Column('original_filename', sa.String(length=500), nullable=False, server_default=''),
    )
    with op.batch_alter_table('books') as batch_op:
        batch_op.alter_column('original_filename', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'original_filename')
    # ### end Alembic commands ###
