"""add_configs_table

Revision ID: efc35e94c595
Revises: 03989f318419
Create Date: 2026-02-17 19:43:36.168056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc35e94c595'
down_revision: Union[str, Sequence[str], None] = '03989f318419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###

    # Seed default config entries
    conn = op.get_bind()

    seeds = [
        # With defaults
        ("GRADE_MINUTES_MAP",
         '{"1": 15, "2": 10, "3": 0, "4": -20, "5": -25}',
         "Grade to game minutes conversion (JSON: grade_value -> minutes)",
         False),
        ("TOPIC_REVIEW_THRESHOLDS",
         '{"2": 1, "3": 2, "4": 3, "5": 3}',
         "Required repetitions per grade before TopicReview is closed (JSON)",
         False),
        ("HOMEWORK_BONUS_MINUTES_ONTIME",
         "10",
         "Bonus minutes for completing homework on time",
         False),
        ("HOMEWORK_BONUS_MINUTES_OVERDUE",
         "-10",
         "Penalty minutes for overdue homework",
         False),
        ("BONUS_FUND_WEEKLY_TOPUP",
         "15",
         "Number of bonus task slots to add each week",
         False),
        ("DEFAULT_DEADLINE_TIME",
         "20:00",
         "Default time when deadline is date-only (HH:MM)",
         False),
        # Without defaults (required)
        ("TEMP_BOOK_DIR",
         None,
         "Staging folder where users place book files for processing",
         True),
        ("BOOKS_STORAGE_DIR",
         None,
         "Base folder for storing processed books",
         True),
        ("ISSUES_LOG",
         None,
         "Path to the issue log file for logging problems",
         True),
    ]

    for key, value, description, is_required in seeds:
        if value is not None:
            conn.execute(sa.text(
                "INSERT INTO configs (key, value, description, is_required, "
                "created_at, updated_at) "
                "VALUES (:key, :value, :desc, :req, datetime('now'), datetime('now'))"
            ), {"key": key, "value": value, "desc": description, "req": is_required})
        else:
            conn.execute(sa.text(
                "INSERT INTO configs (key, value, description, is_required, "
                "created_at, updated_at) "
                "VALUES (:key, NULL, :desc, :req, datetime('now'), datetime('now'))"
            ), {"key": key, "desc": description, "req": is_required})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    # ### end Alembic commands ###
